### ISSUE TITLE
Potential typo in the instructions in the README

### ISSUE THREAD

**Issue by ioana-blue** [CoderPat/structured-neural-summarization#1]
First, thanks for sharing the code, saved me quite a bit of sweat :)

Second, there might be a typo in the instructions to build the vocabulary files. I'm (wild)guessing that the following lines should refer to the target file (instead of inputs):

```
ognn-build-vocab --with_sequence_tokens \
                 --save_vocab /data/naturallanguage/cnn_dailymail/output.vocab \
                 /data/naturallanguage/cnn_dailymail/split/train/inputs.jsonl.gz
```

should read

```
ognn-build-vocab --with_sequence_tokens \
                 --save_vocab /data/naturallanguage/cnn_dailymail/output.vocab \
                 /data/naturallanguage/cnn_dailymail/split/train/targets.jsonl.gz 
```
if I understand correctly what this vocab file is meant for.

**Comment by CoderPat** [comment]
Thanks for this. Should be fixed
