### ISSUE TITLE
Cannot find submodule `parsers.naturallanguage.gigaword` needed in `convert2graph`

### ISSUE THREAD

**Issue by shandou** [CoderPat/structured-neural-summarization#15]
I am trying to run the script `convert2graph.py`, but was unable to find the required submodule for summary parsing. Could you kindly upload (or point me to the resources) this submodule?

Again, it is `parsers.naturallanguage.gigaword`. Thanks!

**Comment by CoderPat** [comment]
Should be fixed by the latest PR

**Comment by shandou** [comment]
Oh? You meant it is already fixed (or is it going to be fixed)? I still don't see that submodule, though. Would you mind pointing me to the correct location? Thanks 😃

**Comment by CoderPat** [comment]
The file should now be self-contained, so that module is no longer needed

**Comment by shandou** [comment]
Thank you very much 😃
Yes, I was able to run the graph converter and now the model is being trained on a small subset of the cnndm data. Appreciate your work!
