### ISSUE TITLE
'MapDataset' object has no attribute 'output_shapes'

### ISSUE THREAD

**Issue by rainsher** [CoderPat/structured-neural-summarization#26]
Hello,
After I processed the CNNDM data, I started running the train_and_eval.py, but I got an error,''MapDataset' object has no attribute 'output_shapes'', how to solve it? Thanks.

File"/structured-neural-summarization-master/OpenGNN/opengnn/utils/data.py", line 13, in get_padded_shapes
    return tf.contrib.framework.nest.map_structure(lambda shape: shape.as_list(),dataset.output_shapes)
AttributeError: 'MapDataset' object has no attribute 'output_shapes'

**Comment by jacobwwh** [comment]
I ran into the same error. How did you solve it?
