### ISSUE TITLE
Error for Momentum optimizer

### ISSUE THREAD

**Issue by ioana-blue** [CoderPat/structured-neural-summarization#3]
I'm getting an error when I use the momentum optimizer:
`TypeError: __init__() missing 1 required positional argument: 'momentum'`

Initially I thought was some TF API breakage, but I think the culprit is in this line:
https://github.com/CoderPat/structured-neural-summarization/blob/master/train_and_eval.py#L516

`    def optimizer(lr): return optimizer_class(lr)  # **optimizer_params)`

For momentum, the constructor expects more parameters, so I'm guessing the following fixes it:
`       def optimizer(lr): return optimizer_class(lr, **kwargs)`
and the `kwargs` are picked from the above.

**Comment by ioana-blue** [comment]
I guess it's possible  it is a TF API breakage. FWIW I'm using TF 1.12

**Comment by CoderPat** [comment]
I apologize for this. I ran most of my early experiments using the more cumbersome API on the OpenGNN, but decided to upload a more user friendly script to users, and some of these bugs were left unchecked.
Should be fixed in the submitted PR. Feel free to review it. Ill merge it tomorrow.
