### ISSUE TITLE
Hyper parameters to reproduce the method-doc results in the paper

### ISSUE THREAD

**Issue by ioana-blue** [CoderPat/structured-neural-summarization#6]
Do the scripts in the models directory (csharp) use the values of the hyperparameters that were used for the final results in the paper for method-doc?

**Comment by CoderPat** [comment]
I'm not sure. I think the are not exactly the same but should be similar. Neverthless the C# dataset available is no the exact same as the used one (do to licenses, etc..) so there would be no guaranties of optimality of the parameters anyway
